name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: qqw1584913629
          outputs: |
            dist/github-snake.gif?color_snake=green&color_dots=#4aff77,#37d461,#24aa4b,#117834,#00441d&background=#161b22
            dist/github-snake.svg?color_snake=green&color_dots=#4aff77,#37d461,#24aa4b,#117834,#00441d&background=#161b22

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}